README.md

Added SOCIS

---

README.md

Well, here it is. Have a look. :)

Made changes to SOCIS's stipend column

---

README.md

Editing the eligibility condition for DataOne Summer Internship Program

Eligibility condition edit

---

README.md

Added open mainframe project

---

README.md

Added Processing Foundation Fellowship

---

README.md

Added Segment Open Fellowship

---

README.md

Added RARE Incubator Program

---

README.md

Removes BOSS from README.md
Closes #38

Remove BOSS - Bountiful Open Source Summer

---

README.md

This adds BOSS which was removed #39 in a new table for open source competitions.

Add OS Competitions Table

---

README.md

Fixes: #43 #48 #49 #50 #51 #52 #53

More competitions added

---

README.md

Added OSoC

---

README.md

Adds GSSoC to Competitions

---

README.md

FOSSASIA internship programme and GCI moved to competitions section

---

README.md

Please review the edits and add the following program to the list

Added another internship program

---

README.md

Adds GNOME internships

---

README.md

Updates BOSS and OSS World Challenge links

---

README.md

Closes: https://github.com/tapasweni-pathak/SOC-Programs/issues/82

Add Igalia Coding Experience Program

---

README.md

update SOCIS link #27

---

README.md

Add Fixvember to list of open source competitions.
Fixes #86

Add Fixvember to Open Source Competitions.

---

README.md

Update open summer of code link

---

README.md

Update hyperledger internship link

---

README.md

Ref:  https://fossasia.org/internship

[UPDATE]: FOSSASIA Internship is offering stipend this year

---

README.md

Fix <https://github.com/tapaswenipathak/Open-Source-Internships/issues/72>

Add a timeline column

---

README.md
index.html

Add Soc/Woc programs

---

README.md
index.html

Added Google Summer of Earth Engine program

---

README.md

The PR brings in the following updates to the list:
- SOCIS, unlike previous versions, now accepts students of all nationalities and provides a stipend for everyone.
- Add the timeline for SOCIS.
References:
1.  Third FAQ from the top: https://socis.esa.int/frequently-asked-questions/

Update SOCIS Information

---

README.md
index.html

add alibaba summer of code

---

pull_request_template.md

add contribution guide

---

index.html

fix #117 
This PR updates the SOCIS information in index.html

Update SOCIS information in index.html 

---

README.md
index.html

Add MDG Winter Of Code

---

README.md

#133 - added OSI badges

---

README.md
index.html

summer fellowship programme

---

README.md
index.html

Add 24 Pull Requests to list of Open Source Competitions

---

README.md
index.html

add woc programmes

---

README.md
index.html

add tech programmes

---

README.md

Replaced Chinese link with English link.

Alibaba updated EN Link

---

README.md
index.html

The X.Org Endless Vacation of Code (EVoC)

---

README.md
index.html

Linux Foundation Networking Internships

---

README.md
index.html

Radare Summer of Code

---

README.md

Format twitter link in README (fix issue #156)

---

README.md
index.html

Add JSoC and OWASP Code Sprint

---

README.md
index.html

Improve README and add Millenium fellowship to index.html

---

README.md
index.html

Add Linux Kernel Mentorship Program

---

README.md
index.html

Solved Issue #173 & Minor Fixes in README.md

---

README.md
index.html

Feat: add DWoC in university woc's

---

README.md
index.html

Fix links for Hyperledger Internship Program

---

README.md

Update README.md added 4 more Winter of Code program

---

README.md
index.html

The OWASP code sprint has been discontinued

---

README.md

link changed

---

README.md
index.html

Adding MLH Fellowship 

---

README.md

Added 3 more open source programs under Open Source Competitions & University SoC/WoC respectively

---

README.md

Updated links for Millennium Fellowship

Fixes Issue - #228 - Update README.md 

---

README.md

Updated ReaadMe
